apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lb-service-reader
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: fake-loadbalancer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lb-service-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lb-service-reader
subjects:
- kind: ServiceAccount
  name: fake-loadbalancer
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-loadbalancer
  name: fake-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-loadbalancer
  template:
    metadata:
      labels:
        app: fake-loadbalancer
      name: fake-loadbalancer
    spec:
      serviceAccountName: fake-loadbalancer
      containers:
      - image: directxman12/fake-loadbalancer
        name: fake-loadbalancer
        env:
        - name: WATCHED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fake-loadbalancer
  labels:
    app: fake-loadbalancer
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app: fake-loadbalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fake-loadbalancer
  labels:
    service-monitor: sample-server
spec:
  selector:
    matchLabels:
      app: fake-loadbalancer
  endpoints:
  - port: web
    path: '/_metrics'
